# Generated by Django 6.0.7 on 2026-07-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
