# Generated by Django 6.0.7 on 2026-07-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_time',)},
        ),
    ]
