# Generated by Django 6.0.7 on 2026-07-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'booking_time')},
        ),
    ]
